### ISSUE TITLE
Debug Drawing

### ISSUE THREAD

**Issue by stefnotch** [dfkeenan/XenkoToolkit#1]
An easy API for drawing debug shapes would be quite useful. Unity has [something like that](https://docs.unity3d.com/ScriptReference/Debug.DrawLine.html).

I would be willing to implement it, however, what should the signatures and whatnot look like? Which shapes should it support?

This might be useable:
https://github.com/jason-wilmans/Xenko.DebugDrawer/tree/development/Implementation/DebugDrawer

**Comment by dfkeenan** [comment]
Hi @stefnotch ,

Sorry I took so long to reply. I have been thinking about it since you posted the issue. This is one of the things on my "list". (I should probably write the list down somewhere.)

Ideally we could have a static class/methods like `Debug.Drawline`. But I don't think naming the class `Debug` would be great though as that is the name the BCL uses for a class in `System.Diagnostics`.  I was thinking maybe calling it `DebugDraw` and have methods such as `Line`, `Ray`, `Box`, `Sphere` etc. 

For API design maybe something similar to Unitys i.e.:

```csharp
[Conditional("DEBUG")]
public static void Line(Vector3 start, Vector3 end, Color? color = null, float duration = 0.0f,bool depthTest = true)
{
    throw new NotImplementedException();
}
```

As for getting into the rendering pipeline.  There are a number of mechanisms in the Xenko runtime to get the engine to automatically add rendering pipeline plugins/game systems.  My plan was to look into that and create maybe a create a `DebugDrawSystem` with a singleton pattern and the static `DebugDraw` methods are just a wrapper for that i.e.

```csharp
public static class DebugDraw
{
    [Conditional("DEBUG")]
    public static void Line(Vector3 start, Vector3 end, Color? color = null, float duration = 0.0f,bool depthTest = true)
    {
        DebugDrawSystem.Current?.Line(start, end, color, duration, depthTest);
    }
}

public class DebugDrawSystem : GameSystem
{
    protected DebugDrawSystem(IServiceRegistry registry) : base(registry)
    {
    }

    //Set this some how after system is ready. And set to null when shutting down.
    internal static DebugDrawSystem Current {get; private set;}

    public void Line(Vector3 start, Vector3 end, Color? color = null, float duration = 0.0f, bool depthTest = true)
    {
        throw new NotImplementedException();
    }
}
```

I was going to dig deeper. But when I started looking at this on the weekend the git.xenko.com site was down (and still is) so didn't get very far.  FYI I was looking at the physics debug shape rendering stuff for inspiration.

Maybe we can work on this soon.

Cheers,
dfkeenan

**Comment by dfkeenan** [comment]
There is an open pull request on the main Xenko repository to implement such a feature. So closing this issue. 

xenko3d/xenko#517
